In [1]:
import pandas as pd

In [33]:
df = pd.read_csv("https://www.ers.usda.gov/webdocs/DataFiles/48747/Unemployment.csv?v=9115.7")

emp = df[['FIPS', 'State', 'Area_name', 'Civilian_labor_force_2017', 'Employed_2017', 'Unemployed_2017',
       'Unemployment_rate_2017']]
emp

,FIPS,State,Area_name,Civilian_labor_force_2017,Employed_2017,Unemployed_2017,Unemployment_rate_2017
0,0,US,United States,"160,273,906","153,293,830","6,980,076",4.4
1,1000,AL,Alabama,2178243,2081676,96567,4.4
2,1001,AL,"Autauga County, AL",25972,24958,1014,3.9
3,1003,AL,"Baldwin County, AL",92090,88342,3748,4.1
4,1005,AL,"Barbour County, AL",8317,7831,486,5.8
5,1007,AL,"Bibb County, AL",8550,8174,376,4.4
6,1009,AL,"Blount County, AL",24725,23726,999,4.0
7,1011,AL,"Bullock County, AL",4833,4595,238,4.9
8,1013,AL,"Butler County, AL",8941,8446,495,5.5
9,1015,AL,"Calhoun County, AL",45770,43497,2273,5.0
10,1017,AL,"Chambers County, AL",15200,14579,621,4.1
11,1019,AL,"Cherokee County, AL",11340,10877,463,4.1
12,1021,AL,"Chilton County, AL",19257,18470,787,4.1
13,1023,AL,"Choctaw County, AL",4407,4128,279,6.3
14,1025,AL,"Clarke County, AL",7737,7078,659,8.5
15,1027,AL,"Clay County, AL",5796,5544,252,4.3
16,1029,AL,"Cleburne County, AL",5724,5466,258,4.5
17,1031,AL,"Coffee County, AL",20886,19966,920,4.4
18,1033,AL,"Colbert County, AL",23252,22038,1214,5.2
19,1035,AL,"Conecuh County, AL",4487,4212,275,6.1
20,1037,AL,"Coosa County, AL",4380,4174,206,4.7
21,1039,AL,"Covington County, AL",15716,14895,821,5.2
22,1041,AL,"Crenshaw County, AL",6403,6112,291,4.5
23,1043,AL,"Cullman County, AL",37824,36404,1420,3.8
24,1045,AL,"Dale County, AL",19934,19040,894,4.5
25,1047,AL,"Dallas County, AL",15027,13898,1129,7.5
26,1049,AL,"DeKalb County, AL",29570,28239,1331,4.5
27,1051,AL,"Elmore County, AL",37217,35840,1377,3.7
28,1053,AL,"Escambia County, AL",14443,13721,722,5.0
29,1055,AL,"Etowah County, AL",43062,41079,1983,4.6
...,...,...,...,...,...,...,...
3245,72095,PR,"Maunabo Municipio, PR",2947,2438,509,17.3
3246,72097,PR,"Mayaguez Municipio, PR",22569,19416,3153,14.0
3247,72099,PR,"Moca Municipio, PR",10703,9131,1572,14.7
3248,72101,PR,"Morovis Municipio, PR",8025,7030,995,12.4
3249,72103,PR,"Naguabo Municipio, PR",8011,7119,892,11.1
3250,72105,PR,"Naranjito Municipio, PR",7152,6306,846,11.8
3251,72107,PR,"Orocovis Municipio, PR",5094,4368,726,14.3
3252,72109,PR,"Patillas Municipio, PR",4641,3727,914,19.7
3253,72111,PR,"Penuelas Municipio, PR",5991,4945,1046,17.5
3254,72113,PR,"Ponce Municipio, PR",45581,40280,5301,11.6
3255,72115,PR,"Quebradillas Municipio, PR",6059,5103,956,15.8
3256,72117,PR,"Rincon Municipio, PR",4662,3950,712,15.3
3257,72119,PR,"Rio Grande Municipio, PR",16947,15304,1643,9.7
3258,72121,PR,"Sabana Grande Municipio, PR",6366,5294,1072,16.8
3259,72123,PR,"Salinas Municipio, PR",7478,6079,1399,18.7
3260,72125,PR,"San German Municipio, PR",10014,8445,1569,15.7
3261,72127,PR,"San Juan Municipio, PR",132461,123168,9293,7.0
3262,72129,PR,"San Lorenzo Municipio, PR",11903,10378,1525,12.8
3263,72131,PR,"San Sebastian Municipio, PR",10572,8707,1865,17.6
3264,72133,PR,"Santa Isabel Municipio, PR",9734,8417,1317,13.5
3265,72135,PR,"Toa Alta Municipio, PR",26557,24505,2052,7.7
3266,72137,PR,"Toa Baja Municipio, PR",29175,26816,2359,8.1
3267,72139,PR,"Trujillo Alto Municipio, PR",26614,25038,1576,5.9
3268,72141,PR,"Utuado Municipio, PR",6753,5811,942,13.9
3269,72143,PR,"Vega Alta Municipio, PR",9782,8736,1046,10.7
3270,72145,PR,"Vega Baja Municipio, PR",13409,11743,1666,12.4
3271,72147,PR,"Vieques Municipio, PR",3026,2588,438,14.5
3272,72149,PR,"Villalba Municipio, PR",7554,6088,1466,19.4
3273,72151,PR,"Yabucoa Municipio, PR",8996,7510,1486,16.5
3274,72153,PR,"Yauco Municipio, PR",10156,8407,1749,17.2

In [37]:
df = pd.read_csv('https://www.ers.usda.gov/webdocs/DataFiles/48747/PovertyEstimates.csv?v=2529')

pov = df[['FIPStxt', 'POVALL_2017', 'PCTPOVALL_2017', 'MEDHHINC_2017']]

In [40]:
poverty = pov.rename(columns = {'FIPStxt': 'FIPS', 'POVALL_2017': 'Total_poverty_2017', 'PCTPOVALL_2017': 'Poverty_rate_2017',
                               'MEDHHINC_2017': 'Median_income_2017'})

poverty

       FIPS Total_poverty_2017  Poverty_rate_2017 Median_income_2017
0         0         42,583,651               13.4             60,336
1      1000            802,263               16.9             48,193
2      1001              7,390               13.4             58,343
3      1003             21,199               10.1             56,607
4      1005              7,414               33.4             32,490
5      1007              4,137               20.2             45,795
6      1009              7,343               12.8             48,253
7      1011              2,956               34.4             29,113
8      1013              4,154               21.3             36,842
9      1015             19,832               17.7             45,937
10     1017              6,036               18.2             36,883
11     1019              4,381               17.2             44,842
12     1021              7,303               16.8             46,405
13     1023              3,031               23.7             36,711
14     1025              5,541               23.3             36,719
15     1027              2,363               18.1             39,642
16     1029              2,365               16.1             45,480
17     1031              7,954               15.5             51,998
18     1033              8,324               15.4             46,100
19     1035              2,939               23.7             30,796
20     1037              1,823               17.4             42,442
21     1039              6,447               17.7             39,093
22     1041              2,722               19.9             38,419
23     1043             11,256               13.8             45,925
24     1045              8,528               17.7             42,572
25     1047             10,796               27.9             31,329
26     1049             13,785               19.5             39,906
27     1051              9,151               12.0             59,652
28     1053              7,971               23.3             37,870
29     1055             18,257               18.1             41,791
...     ...                ...                ...                ...
3164  55131              7,124                5.3             76,551
3165  55133             19,090                4.8             82,627
3166  55135              5,269               10.6             58,474
3167  55137              2,819               12.2             47,653
3168  55139             18,076               11.1             57,529
3169  55141              7,704               10.7             53,346
3170  56000             61,319               10.8             61,279
3171  56001              7,075               19.5             44,745
3172  56003              1,433               12.2             50,380
3173  56005              4,271                9.4             78,240
3174  56007              1,723               11.9             60,634
3175  56009              1,260                9.2             65,469
3176  56011                565                7.7             61,664
3177  56013              6,291               16.2             50,134
3178  56015              1,572               12.9             51,023
3179  56017                556               12.1             47,775
3180  56019                792                9.5             55,412
3181  56021              9,294                9.7             61,658
3182  56023              1,464                7.6             65,137
3183  56025              8,631               11.1             61,049
3184  56027                290               13.4             45,768
3185  56029              2,694                9.4             57,619
3186  56031                881               10.4             50,775
3187  56033              2,673                9.1             54,482
3188  56035                643                6.6             74,811
3189  56037              4,253               10.0             75,590
3190  56039              1,348                5.8             90,145
3191  56041              2,067               10.2             67,404
3192  56043                845               10.7             57,989
3193  56045                699               10.6             56,214

[3194 rows x 4 columns]

In [41]:
result = pd.merge(emp, poverty, how = 'inner', on = 'FIPS', validate = '1:1')
result

,FIPS,State,Area_name,Civilian_labor_force_2017,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Total_poverty_2017,Poverty_rate_2017,Median_income_2017
0,0,US,United States,"160,273,906","153,293,830","6,980,076",4.4,"42,583,651",13.4,"60,336"
1,1000,AL,Alabama,2178243,2081676,96567,4.4,"802,263",16.9,"48,193"
2,1001,AL,"Autauga County, AL",25972,24958,1014,3.9,"7,390",13.4,"58,343"
3,1003,AL,"Baldwin County, AL",92090,88342,3748,4.1,"21,199",10.1,"56,607"
4,1005,AL,"Barbour County, AL",8317,7831,486,5.8,"7,414",33.4,"32,490"
5,1007,AL,"Bibb County, AL",8550,8174,376,4.4,"4,137",20.2,"45,795"
6,1009,AL,"Blount County, AL",24725,23726,999,4.0,"7,343",12.8,"48,253"
7,1011,AL,"Bullock County, AL",4833,4595,238,4.9,"2,956",34.4,"29,113"
8,1013,AL,"Butler County, AL",8941,8446,495,5.5,"4,154",21.3,"36,842"
9,1015,AL,"Calhoun County, AL",45770,43497,2273,5.0,"19,832",17.7,"45,937"
10,1017,AL,"Chambers County, AL",15200,14579,621,4.1,"6,036",18.2,"36,883"
11,1019,AL,"Cherokee County, AL",11340,10877,463,4.1,"4,381",17.2,"44,842"
12,1021,AL,"Chilton County, AL",19257,18470,787,4.1,"7,303",16.8,"46,405"
13,1023,AL,"Choctaw County, AL",4407,4128,279,6.3,"3,031",23.7,"36,711"
14,1025,AL,"Clarke County, AL",7737,7078,659,8.5,"5,541",23.3,"36,719"
15,1027,AL,"Clay County, AL",5796,5544,252,4.3,"2,363",18.1,"39,642"
16,1029,AL,"Cleburne County, AL",5724,5466,258,4.5,"2,365",16.1,"45,480"
17,1031,AL,"Coffee County, AL",20886,19966,920,4.4,"7,954",15.5,"51,998"
18,1033,AL,"Colbert County, AL",23252,22038,1214,5.2,"8,324",15.4,"46,100"
19,1035,AL,"Conecuh County, AL",4487,4212,275,6.1,"2,939",23.7,"30,796"
20,1037,AL,"Coosa County, AL",4380,4174,206,4.7,"1,823",17.4,"42,442"
21,1039,AL,"Covington County, AL",15716,14895,821,5.2,"6,447",17.7,"39,093"
22,1041,AL,"Crenshaw County, AL",6403,6112,291,4.5,"2,722",19.9,"38,419"
23,1043,AL,"Cullman County, AL",37824,36404,1420,3.8,"11,256",13.8,"45,925"
24,1045,AL,"Dale County, AL",19934,19040,894,4.5,"8,528",17.7,"42,572"
25,1047,AL,"Dallas County, AL",15027,13898,1129,7.5,"10,796",27.9,"31,329"
26,1049,AL,"DeKalb County, AL",29570,28239,1331,4.5,"13,785",19.5,"39,906"
27,1051,AL,"Elmore County, AL",37217,35840,1377,3.7,"9,151",12.0,"59,652"
28,1053,AL,"Escambia County, AL",14443,13721,722,5.0,"7,971",23.3,"37,870"
29,1055,AL,"Etowah County, AL",43062,41079,1983,4.6,"18,257",18.1,"41,791"
...,...,...,...,...,...,...,...,...,...,...
3163,55131,WI,"Washington County, WI",77919,75760,2159,2.8,"7,124",5.3,"76,551"
3164,55133,WI,"Waukesha County, WI",226645,220114,6531,2.9,"19,090",4.8,"82,627"
3165,55135,WI,"Waupaca County, WI",26663,25815,848,3.2,"5,269",10.6,"58,474"
3166,55137,WI,"Waushara County, WI",11442,10987,455,4.0,"2,819",12.2,"47,653"
3167,55139,WI,"Winnebago County, WI",93837,91051,2786,3.0,"18,076",11.1,"57,529"
3168,55141,WI,"Wood County, WI",35107,33793,1314,3.7,"7,704",10.7,"53,346"
3169,56000,WY,Wyoming,292923,280689,12234,4.2,"61,319",10.8,"61,279"
3170,56001,WY,"Albany County, WY",20465,19879,586,2.9,"7,075",19.5,"44,745"
3171,56003,WY,"Big Horn County, WY",5359,5132,227,4.2,"1,433",12.2,"50,380"
3172,56005,WY,"Campbell County, WY",23018,21897,1121,4.9,"4,271",9.4,"78,240"
3173,56007,WY,"Carbon County, WY",7900,7584,316,4.0,"1,723",11.9,"60,634"
3174,56009,WY,"Converse County, WY",7480,7147,333,4.5,"1,260",9.2,"65,469"
3175,56011,WY,"Crook County, WY",3683,3554,129,3.5,565,7.7,"61,664"
3176,56013,WY,"Fremont County, WY",19347,18275,1072,5.5,"6,291",16.2,"50,134"
3177,56015,WY,"Goshen County, WY",6922,6723,199,2.9,"1,572",12.9,"51,023"
3178,56017,WY,"Hot Springs County, WY",2332,2241,91,3.9,556,12.1,"47,775"
3179,56019,WY,"Johnson County, WY",4195,4020,175,4.2,792,9.5,"55,412"
3180,56021,WY,"Laramie County, WY",48205,46440,1765,3.7,"9,294",9.7,"61,658"
3181,56023,WY,"Lincoln County, WY",8747,8426,321,3.7,"1,464",7.6,"65,137"
3182,56025,WY,"Natrona County, WY",39516,37445,2071,5.2,"8,631",11.1,"61,049"
3183,56027,WY,"Niobrara County, WY",1301,1265,36,2.8,290,13.4,"45,768"
3184,56029,WY,"Park County, WY",15687,15020,667,4.3,"2,694",9.4,"57,619"
3185,56031,WY,"Platte County, WY",4775,4598,177,3.7,881,10.4,"50,775"
3186,56033,WY,"Sheridan County, WY",15795,15180,615,3.9,"2,673",9.1,"54,482"
3187,56035,WY,"Sublette County, WY",4255,4064,191,4.5,643,6.6,"74,811"
3188,56037,WY,"Sweetwater County, WY",21555,20576,979,4.5,"4,253",10.0,"75,590"
3189,56039,WY,"Teton County, WY",15418,14983,435,2.8,"1,348",5.8,"90,145"
3190,56041,WY,"Uinta County, WY",9103,8689,414,4.5,"2,067",10.2,"67,404"
3191,56043,WY,"Washakie County, WY",4112,3947,165,4.0,845,10.7,"57,989"
3192,56045,WY,"Weston County, WY",3754,3605,149,4.0,699,10.6,"56,214"